client/config.js, client/src/elements/schema-editor/schema-editor-color.css, client/src/elements/schema-editor/schema-editor-color.html, client/src/elements/schema-editor/schema-editor-wrapper.html
Looks like that: 
In tool schema `"Q:type": "color"` has to be specified.
=> Add color picker input field support

client/src/elements/item-preview/item-preview.html, client/src/elements/molecules/radio-button-group.css, client/src/elements/molecules/radio-button-group.html, client/src/elements/schema-editor/schema-editor-select.html, client/src/elements/schema-editor/schema-editor-select.js, client/src/styles/q-form.css
```
"type": "string",
"enum": ["a", "b"],
"Q:options": {
"selectType": "radio"
}
```
results in radio buttons instead of select element.
=> feat: select option to show radiobuttons instead of dropdown

client/config.js, client/package.json, client/src/dialogs/account-dialog.html, client/src/main.js, client/src/resources/Auth.js, client/src/resources/Item.js, client/src/resources/ItemStore.js, client/src/resources/User.js
If `editorConfig.authConfig.type === 'token'` (coming from Q-server) then we use aurelia-authentication to handle a token coming from `/authenticate`. aurelia-authentication adds an interceptor to aurelia-fetch-client, so the token is added to all the requests that use aurelia-fetch-client.
this is all only loaded if the authConfig.type is set to `token`. Otherwise the current functionality stays untouched.
This implements #3
=> Feat token auth

client/src/elements/schema-editor/schema-editor-array.html, client/src/elements/schema-editor/schema-editor-array.js
This would fix the issue with the handling of existing items of a tool that got a new property of type array.
We have 3 options to solve the issue (probably more that did not came to my mind):
1. force the tool implementor to run a migration in these cases
2. somehow apply any new defaults to existing items when opening them in editor
3. make sure that we have an array in schema-editor-array if the data value is `undefined`
This PR implements 3.
Not sure if this is really the best solution.
I like it because it makes extending options on tools easier (because one does not have to write and run a migration). It works the same for `string` and other primitive types (where we do not fail if we have `undefined`). It is not destructive as it only overwrites the property if it is `undefined`. …
=> fix: ensure data is an array in schema-editor-array

client/locales/de/translation.json, client/locales/en/translation.json, client/src/dialogs/account-dialog.html, client/src/dialogs/account-dialog.js, client/src/elements/item-preview/item-preview.html, client/src/elements/item-preview/item-preview.js, client/src/elements/organisms/meta-editor.html, client/src/elements/organisms/meta-editor.js, client/src/resources/Item.js, client/src/resources/ItemStore.js
This needs an additional property in Q-server editor config like this:
```
publications: [
{
key: 'nzz',
label: 'NZZ',
previewTarget: 'nzz_ch'
}
]
```
where the target is the key of a target configured in target config.
The user can set her publication in account-dialog. If it is defined, the user will see the target configured for her publication in the preview.
There is no direct connection between publication and target as there can be multiple targets per publication (website, app, amp etc..)
=> feat: add publication filter to be configured by Q-server editor config.

client/config.js, client/locales/de/translation.json, client/locales/en/translation.json, client/package.json, client/src/elements/schema-editor/schema-editor-files.css, client/src/elements/schema-editor/schema-editor-files.html, client/src/elements/schema-editor/schema-editor-files.js, client/src/elements/schema-editor/schema-editor-wrapper.html
Use this in a schema like this:
```
{
"type": "array",
"Q:type": "files",
"Q:options": {
"acceptedFiles": "image/*"
"fileProperties": {
"url": "url",
"key": "key",
"size": "size",
"width": "width",
"height": "height"
}
},
"items": {
"type": "object"
}
}
```
or like this
```
{
"type": "object",
"Q:type": "files",
"Q:options": {
"maxFiles": 1,
"acceptedFiles": "image/*",
"fileProperties": {
"url": "url",
"key": "key",
"size": "size",
"width": "width",
"height": "height"
}
}
}
```
The property needs to be an object if `maxFiles` is 1, otherwise it needs to be an array of objects.
`maxFiles` is optional in this case and defaults to no limit.
What gets stored is an object/array of objects with the properties mapped in `fileProperties` option. So in this example it would be something like
```
{ …
```
=> (schema-editor) add schema-editor-files to upload one or many files

README.md, client/config.js, client/env, client/package.json, client/src/elements/atoms/button-no.html, client/src/elements/atoms/button-primary.html, client/src/elements/atoms/button-secondary.html, client/src/elements/atoms/button-tertiary.html, client/src/elements/atoms/button-yes.html, client/src/elements/atoms/icon-button.html, client/src/elements/atoms/icon-button.js, client/src/elements/atoms/index.js, client/src/elements/schema-editor/schema-editor-geojson-point.css, client/src/elements/schema-editor/schema-editor-geojson-point.js, client/src/pages/login.html
this changes the geocoding provider to opencagedata because mapzen is shutting down.
this needs the following editor config delivered from Q server:
```
schemaEditor: {
geojson: {
layer: {...}
opencagedata: {
apiKey: '',
language: ''
}
}
}
```
=> (schema-editor) use opencagedata instead of mapzen as geocoding provider

client/src/elements/schema-editor/schema-editor-link.html, client/src/elements/schema-editor/schema-editor-link.js, client/src/elements/schema-editor/schema-editor-number.html, client/src/elements/schema-editor/schema-editor-string.html, client/src/elements/schema-editor/schema-editor-string.js, client/src/elements/schema-editor/schema-editor-textarea.html, client/src/elements/schema-editor/schema-editor-textarea.js, client/src/elements/schema-editor/schema-editor-url.html, client/src/elements/schema-editor/schema-editor-url.js, client/src/styles/q-form.css
implements: https://github.com/nzzdev/Q-editor/issues/46
Placeholder is configurable via Q:options like this:
```
"someProperty": {
"title": "",
"type": "number",
"Q:options": {
"placeholder": "123"
}
},
```
=> (schema-editor) input placeholder configurabel via Q:options

README.md, client/locales/de/translation.json, client/locales/en/translation.json, client/src/dialogs/confirm-dialog.html, client/src/dialogs/confirm-dialog.js, client/src/pages/item-overview.js
This will ask the user if she really wants to edit if an item is active and has not been edited since a configurable amount of time before opening the editor from item-overview page.
it's deployed on staging for testing.
=> Feat confirm before edit

CHANGELOG.md, index.js, package-lock.json, package.json
hotfix: do not parse cookies as we do not need them and there was an error last night for someone with a probably broken cookie who was not able to embed a graphic because Q-editor returned with 400.
=> Release 1.7.2

client/src/livingdocs-component-app/app.js, client/src/pages/index.js, client/src/resources/ItemStore.js
- This PR moves the search implementation to the q-server
- There is now an endpoint which takes requests in the following form:
```http
GET /search?
tool=imageslider&
createdBy=manuel.roth@nzz.ch&
department=Storytelling%20/%20Infografik&
publication=nzz&
searchString=Bundesrat&
limit=18
```
=> Move search implementation to q-server

client/src/livingdocs-component-app/app.css, client/src/livingdocs-component-app/app.html, client/src/pages/index.html
- Center aligns empty list message in livingdocs-component
- Hides empty list message while loading
- This is deployed on test environment🎉 -> https://q.st-test.nzz.ch/index / https://q.st-test.nzz.ch/livingdocs-component.html
=> Adjustments to items-list

client/src/value-converters/ToolTValueConverter.js
- This PR improves the `ToolTValueConverter` so that undefined values are not getting translated
- Currently this can result in undefined being shown in the schema editor:
- This branch is deployed on https://q.st-test.nzz.ch/editor/map
=> Don't try to translate undefined values

client/src/elements/atoms/button-primary.css, client/src/elements/atoms/button-primary.html, client/src/elements/atoms/button-secondary.css, client/src/elements/atoms/button-secondary.html, client/src/elements/atoms/button-tertiary.css, client/src/elements/atoms/button-tertiary.html, client/src/elements/atoms/icon-button.css, client/src/elements/atoms/icon-button.html, client/src/elements/atoms/icon-button.js, client/src/elements/organisms/tool-status-bar.html, client/src/elements/organisms/tool-status-bar.js, client/src/pages/editor.js, client/src/resources/Item.js, client/src/styles/app.css
- never tries to save an item if it's currently saving
- disable save/activate/deactivate buttons in editor tool-status-bar if the item is currently saving
- needed some refactoring around the click event binding on the buttons, this is not perfect yet.
=> (editor) fix double save

client/src/elements/schema-editor/schema-editor-table.js
- This PR sets the copy limit to 10000 rows and 100 columns
- @benib already tried to fix this (https://github.com/nzzdev/Q-editor/commit/be028ed9924343c3890e8b43c94f3f05b32e0322#diff-bb27bc2e1da8715ed44267c6f807b554), but the `copyRowsLimit` was replaced with `copyPaste` option in some version of handsontable (see github issue discussion [here](https://github.com/handsontable/handsontable/issues/3524)). Unfortunately they haven't updated the documentation yet.
- This branch will be deployed on staging as soon as https://github.com/nzzdev/Q-editor/pull/154 was reviewed
=> Allow to copy 10000 rows and 100 columns

client/env, client/src/elements/item-preview/item-preview.js, client/src/elements/item-preview/preview-container.js, client/src/livingdocs-component-app/app.js
- This PR implements constructing a sophie build service link out of the sophie modules array provided in the renderingInfo
- Closes https://github.com/nzzdev/Q-editor/issues/159
- Tested locally, will be deployed in st-test as soon as other PRs are merged
=> Create sophie link out of sophie modules array

client/src/elements/item-preview/item-preview.js
- This PR fixes a long standing bug with the preview. The preview always loaded twice when changing the preview size. 
- The preview size is set twice on the `previewWidthProxy` when switching between previewWidths ([because of two-way data binding](https://github.com/nzzdev/Q-editor/blob/dev/client/src/elements/item-preview/item-preview.html#L9))
- This PR fixes this by only updating the value if it is different from previous value
- Closes https://github.com/nzzdev/Q-editor/issues/92
=> Fix multiple preview loading on size change

client/src/pages/editor.js
- This is using the History API to append the item id to the url if it's not there yet
- This happens when a new item is saved for the first time as we do not know the id before the first save
- This is implemented as sometimes people send links to their graphic (because they have a question/problem) but the id is not yet part of it as they never left the editor after creating the new graphic
deployed on test env.
=> (editor) append item id to url after first save

client/src/livingdocs-component-app/app.css, client/src/livingdocs-component-app/app.html, client/src/livingdocs-component-app/app.js, client/src/livingdocs-component-main.js
- This PR implements using schema-editor for displayOptions in ld preview (availability checks work as well)
- Can be tested by going to https://q.st-test.nzz.ch/livingdocs-component.html and select an active chart item
=> Use schema-editor for displayOptions in ld preview

client/src/resources/IdGenerator.js, client/src/resources/Item.js, client/src/resources/ItemActionController.js, client/src/resources/ItemStore.js, client/src/resources/ObjectFromSchemaGenerator.js
- fixes #62 
- this refactors the blueprinting like this:
- do not just copy the data and changing some properties
- instead generate a new object based on the tools schema
- all properties that are available on the original object but not defined in the schema will be removed
- any property that has `generatedId` as the `Q:default` will be regenerated based on the new id
This can be tested with our quiz tool (the id of the single questions needs to be regenerated on blueprinting based on the new id).
=> Fix regenerate ids on blueprint

client/src/livingdocs-component-app/app.css, client/src/livingdocs-component-app/app.html
- This PR makes the action buttons in ld preview more compact (so there is more space available for the displayOptions)
=> Make action buttons in ld preview more compact

CHANGELOG.md, client/src/elements/schema-editor/schema-editor-wrapper.js, package-lock.json, package.json
- This PR changes schema-editor-wrapper to run the `availability-checks`when ever the schema changes
- In the livingdocs component we use the schema-editor for the displayOptions and change the displayOptionsSchema when the user changes between items. But the availability-checks ran only once when attached. This resulted in false displayOptions
- This branch is deployed on staging for testing -> https://q.st-staging.nzz.ch/livingdocs-component.html
=> Release 3.5.1

client/src/elements/schema-editor/schema-editor-table.js
- implements https://github.com/nzzdev/Q-editor/issues/173
- we do not trim all cells values (this could be a reasonable feature as well) but only trim to test if it contains only whitespace and set the cells value to `null` in this case. `null` values then get trimmed from the matrix (removed only if outside the part containing data) when the data changes.
=> (schema-editor-table) trim whitespace only cells

client/src/elements/schema-editor/schema-editor-files.js
- Images which where uploaded before we added the type property don't properly show a thumbnail at the moment:
- This PR adds a check if the type property is available and falls back to a gray thumbnail if the type is not set:
=> Checks if file has type before checking if its an image

client/src/livingdocs-component-app/app.js
- This PR replaces promise chaining syntax with async/await in livingdocs component
- Loads the QServerBaseUrl only once and sets it as class attribute
- Makes `getItem` a function of the App class
- There will be more PR's refactoring the ld-component step by step
- This branch is deployed on [st-test](https://q.st-test.nzz.ch/livingdocs-component.html)
=> Convert promise chains to async/await in ld component

client/src/livingdocs-component-app/app.html, client/src/livingdocs-component-app/app.js
- Before we were keeping track of all the items that were selected in the ld-component. This is not necessary. This PR replaces the `selectedItems` array with a single property saving the currently `selectedItem`
- This branch is deployed on [st-test](https://q.st-test.nzz.ch/livingdocs-component.html)
=> Replace selectedItems array with single selectedItem property

client/src/livingdocs-component-app/app.html, client/src/livingdocs-component-app/app.js
- This PR adds the `appendItemToPayload` query string to the displayOptionsSchema request, if the tool sets the property `hasDynamicDisplayOptions`
- This branch is deployed on st-test. This can be tested by updating the displayOptionsSchema of [this item](https://q.st-test.nzz.ch/item/cd11d746cd1d1b6018d83e00b75db4ab) and checking the change [here](https://q.st-test.nzz.ch/livingdocs-component.html)
=> Appends item to request if tool supports dynamic displayOptions

client/config.js, client/package.json, client/src/elements/schema-editor/schema-editor-code.html, client/src/elements/schema-editor/schema-editor-code.js, client/src/elements/schema-editor/schema-editor-wrapper.html
- This implements a new `schema-editor-code` component
- Currently this uses codemirror, but could be changed to something else if we want
- Codemirror is lazy loaded when a schema-editor-code is attached to not bloat the bundle
- We only load html, javascript and jinja2 modes at the moment. This could be made configurable in the future if we see the need.
- The mode for codemirror is set by option `mode` or `mimeType` from the options in the tool schema
See https://github.com/nzzdev/Q-custom-code/pull/33 for an example how this is configured.
=> Feat schema editor code

CHANGELOG.md, client/config.js, client/package.json, client/src/elements/schema-editor/schema-editor-code.html, client/src/elements/schema-editor/schema-editor-code.js, client/src/elements/schema-editor/schema-editor-wrapper.html, client/src/livingdocs-component-app/app.html, client/src/livingdocs-component-app/app.js, package-lock.json, package.json
- feature: new schema-editor-code (`"Q:type": "code"`) using codemirror to show a code editor, currently supports javascript and html mime types.
- feature: `appendItemToPayload` is used appended to the request for `display-options-schema.json` in livingdocs-component if tool config sets `hasDynamicDisplayOptions` to true.
=> Release 3.7.0

client/src/elements/schema-editor/schema-editor-code.js
- this makes the mime type `text/css` correctly syntax highlighted in schema-editor-code
- not deployed but can be locally tested by adding a string with `"Q:type": "code"` and `"mimeType":"text/css"` in the `Q:options` to any tool schema (likely to be used in Q-custom-code).
@manuelroth I would like to merge this to dev and release later with the tasks feature currently in development if we do not need it earlier on prod.
=> (schema-editor-code): load css codemirror module

CHANGELOG.md, client/src/elements/schema-editor/schema-editor-code.js, client/src/elements/schema-editor/schema-editor.js, package-lock.json, package.json
- fix: load css codemirror module
- fix: fix default binding for objects on schema-editor to not fail if top level object is undefined (e.g. new options property on item)
deployed on staging.
=> Release 3.7.1

client/src/elements/item-preview/item-preview.css, client/src/livingdocs-component-app/app.css
- this stops the preview container from growing to overlap it's container in height
- deployed on staging and to be tested by selecting items that are very high in the livingdocs-component or in Q editor
=> Fix preview container height

client/src/elements/schema-editor/schema-editor-array.css, client/src/elements/schema-editor/schema-editor-array.html, client/src/elements/schema-editor/schema-editor-array.js, client/src/elements/schema-editor/schema-editor-object.css, client/src/elements/schema-editor/schema-editor-object.html, client/src/elements/schema-editor/schema-editor-object.js, client/src/elements/schema-editor/schema-editor-select.html, client/src/elements/schema-editor/schema-editor.css, client/src/pages/editor.css, client/src/pages/editor.html, client/src/styles/config.css
- changes some of the css to improve the schema-editor visual structure in the options pane.
- adds a 2 layout options:
schema-editor-array supports
```
{
"Q:options": {
layout: "compact"
}
}
```
This results in a more compact array layout, using an icon button to delete elements instead of a button with text.
schema-editor-object supports
```
{
"Q:options": {
expandable: true
}
}
```
Resulting in the all input elements inside of an element being hidden behind an expand-button (as is already supported in schema-editor-array).
These new options are used in the upcoming Q-chart release and can be tested on testing env using the chart tool.
=> Feat schema editor structure improvements

CHANGELOG.md, client/src/elements/schema-editor/schema-editor-array.html, client/src/livingdocs-component-app/app.js, package-lock.json, package.json
- fix: load the additional editor stylesheets (used to load fonts needed for previews) in livingdocs-component.html to show a correct preview
- fix: show the add element button in schema-editor-array if the array value is null
This branch is deployed on stage environment.
=> Release 4.0.3

client/src/elements/item-preview/item-preview.js
In the current version of the editor, the user needs to have a publication assigned, otherwise the item preview doesn't work at all.
The changes in here makes the publication on the user object optional and falls back to the first configured target.
=> Fall back to the first available target for the item preview

CHANGELOG.md, client/config.js, client/package.json, client/src/dialogs/export-dialog.css, client/src/dialogs/export-dialog.html, client/src/dialogs/export-dialog.js, client/src/elements/atoms/button-primary.html, client/src/elements/atoms/button-secondary.html, client/src/elements/atoms/button-tertiary.html, client/src/elements/atoms/icon-button.html, client/src/elements/atoms/icon-button.js, client/src/elements/atoms/q-loader.html, client/src/elements/item-preview/item-preview.js, client/src/elements/item-preview/preview-container.html, client/src/elements/item-preview/preview-container.js, client/src/pages/item-overview.css, client/src/pages/item-overview.html, client/src/pages/item-overview.js, client/src/resources/QTargets.js, package-lock.json, package.json
- feat: exportable targets. targets configured as exportable get a button on the item-overview page opening a modal allowing to download the renderingInfo of this target
- feat: buttons take an isLoading parameter to show a spinner when they are busy
- fix: if the user has no default preview target defined through the publication config, the first available target is used for the preview
=> Release 4.1.0

client/config.js, client/package.json, client/src/dialogs/export-dialog.js
*This improves the export dialog*
- file extension is taken from the content-type of the renderingInfo response now
- file title contains a slugified variant of the item title along the id
- mime-db and slugify get loaded when the export dialog opens
=> Feat export improvements

client/src/dialogs/export-dialog.html, client/src/dialogs/export-dialog.js, client/src/pages/item-overview.js
- the userExportable config can contain `download.file.nameMaxLength` to limit the length of the filename
- this needs to be done because Woodwing has a problem with filenames longer than 60 characters
- Our server dev branch already contains the config for this
- This needs to be released before September 30th
=> (export) allow limit of downloaded file name length

client/locales/de/translation.json, client/locales/en/translation.json, client/locales/fr/translation.json, client/src/dialogs/schema-editor-dialog.html, client/src/dialogs/schema-editor-dialog.js, client/src/elements/schema-editor/helpers.js, client/src/elements/schema-editor/schema-editor-dialog.css, client/src/elements/schema-editor/schema-editor-dialog.html, client/src/elements/schema-editor/schema-editor-dialog.js, client/src/elements/schema-editor/schema-editor-wrapper.html, client/src/styles/q-dialog.css
This PR implements the component `schema-editor-dialog`. It allows to open a part of the schema in a dialog:
- The tool schema can define the `Q:options` property `openInDialog` to define that this subtree of the schema should be open in a dialog:
```json
{
"bbox": {
"title": "Sichtbarer Kartenausschnitt",
"Q:type": "bbox",
"Q:options": {
"openInDialog": true,
"openInDialog": {  // Or if you want to define a custom button text
"buttonText": "Kartenbereich definieren"
}
},
"type": "array",
"maxItems": 4,
"items": {
"type": "number"
}
}
}
```
The component displays a button with default text "Open dialog" or a custom text:
Opening the dialog will render the sub-schema in a new schema-editor:
- The changes can be saved or canceled
- HTML Form validation for required fields will be trigger on …
=> Implements component schema-editor-dialog

client/src/elements/organisms/q-bar.css, client/src/pages/editor.html, client/src/pages/index.css, client/src/pages/index.html, client/src/pages/item-overview.html
- this allows to navigate from editor to item-overview by clicking the back button (took you to index before)
- the Q logo is added to all header bars to bring you directly to index page
=> (q-bar) add Q logo to the header on all screens for navigation

client/src/livingdocs-component-app/app.js
This PR implements using the new item specific display-options route. This route also handles dynamic-display options. Therefore the property `hasDynamicDisplayOptions` is removed in Q-Editor and the toolConfig in Q-Server-NZZ. 
Can be tested here: https://edit-stage.nzz.ch/articles/1276263/edit/component/doc-1dn82bmc30/include/q-embed/0
=> (livingdocs-component) use item specific display-options route

client/src/pages/item-overview.css
- when there are multiple export buttons on the item overview page, the spacing between these buttons was missing
- this PR adds the same margin after these buttons as is in place for the other buttons in this sidebar.
=> (item overview) adds spacing between multiple export buttons

client/src/elements/item-preview/preview-container.js
This fixes a bug where the imageElement in the preview was removed from the previewElement at the wrong spot where it was already gone.
=> (preview) fix the preview of image type rendering info

CHANGELOG.md, client/src/elements/organisms/tool-selection.js
- show only the selected tools also if the users config still contains tools that are not available anymore
=> (tool selection) show only the selected tools

CHANGELOG.md, client/src/elements/organisms/tool-selection.js, package-lock.json, package.json
- fix: show only the selected tools also if the users config still contains tools that are not available anymore
=> Release 6.1.2

client/src/elements/item-preview/item-preview.css, client/src/livingdocs-component-app/app.css
This PR adjusts the preview padding to new size (24px on each side).
This PR is deployed on st-test: https://q.st-test.nzz.ch/item/chart-40
=> Adjust preview padding to new size

client/src/dialogs/schema-editor-dialog.js, client/src/elements/schema-editor/schema-editor-bbox.js, client/src/elements/schema-editor/schema-editor-geojson-point.js, client/src/pages/editor.js, client/src/resources/checkers/ToolEndpointChecker.js
- This PR does the following:
- Awaits ToolEndpointChecks before rendering the preview. This change is necessary for the highlight region feature in the maps tool
- Increases time to input region name in geojson-compontent to 1s
- Adds an optional property `bounds` to the bbox-component, which allows the tool to define a bound in the schema.
- This PR is deployed on staging -> https://q.st-staging.nzz.ch/editor/locator_map/6dcf203a5c5f74b61aeea0cb0e45692d
=> Improves ToolEndpointChecks and geojson-component search input

CHANGELOG.md, README.md, client/src/elements/item-preview/item-preview.js, package-lock.json, package.json
Before this fix, the following was happening on the item-overview page:
- `loadPreview()` is called from `targetProxy` when `target` is set
- `loadPreview()` is called again from the `attached()` life-cycle hook
As far as I can tell, the call from attached() was not required; the preview is still working on the overview page and inside the editor.
Deployed on staging, [the test item](https://q.st-staging.nzz.ch/item/6dcf203a5c5f74b61aeea0cb0eef8942) now only loads once.
Fixes #235
=> Release 6.2.5

client/src/elements/schema-editor/schema-editor-table.js
Discovered a bug when writing predefined content to data table:
* before: when gathering predefined values the predefined content array holding readOnly information was overwritten
* fixed: map original array to gather values to a new array and keep original
Can be tested on `test` (on `staging` one can see the old behavior of not having readOnly cells).
=> fix for readonly cells

client/src/elements/schema-editor/schema-editor-table.js
This PR improves the `isOverwritingAllowed` function. Rows and columns which are not in the range of the predefinedValues array will be ignored. The old behaviour was preventing switching between basemaps which have different dimentions (Switzerland has 26 Cantons and Germany has 401 Landkreise)
This change can be tested by comparing the behaviour on test and staging. This branch is deployed on test and can be tested by creating a new choropleth map and switching the basemap from Germany back to Switzerland. On staging the old editor is deployed and switching back doesn't work.
=> Ignore rows/columns which differ of range of predefinedValues

CHANGELOG.md, client/src/resources/checkers/ToolEndpointChecker.js, package-lock.json, package.json
Fixes https://github.com/nzzdev/Q-editor/issues/292
This branch is deployed on [staging](https://q.st-staging.nzz.ch/item/choropleth-17) for testing. Before this change empty responses from ToolEndpoint requests were treated as errors. After this change empty responses are allowed and not treated as errors anymore.
=> Release v6.3.3

client/src/elements/schema-editor/schema-editor-geojson-point.js
**test steps**
1. Open q
2. Create map
3. Add point
4. Enter 'Donezk' in geolocation search field (top right on mapbox map)
5. Entry with 'Donezk' as name should appear (latin instead of cyrillic characters)
=> Specify user language for geolocator query results to de & en
