nzzdev/Q-editor

client/src/elements/schema-editor/schema-editor-base64image.html, client/src/elements/schema-editor/schema-editor-base64image.js, client/src/elements/schema-editor/schema-editor-lat-lng.html, client/src/elements/schema-editor/schema-editor-lat-lng.js, client/src/elements/schema-editor/schema-editor-link.js, client/src/elements/schema-editor/schema-editor-number.js, client/src/elements/schema-editor/schema-editor-wrapper.html
This fixes #6 and the same bug for some other types.
=> fixes required attribute handling for several schema-editor types

client/build/bundles.js, client/config.js, client/package.json, client/src/elements/organisms/tool-selection.html, client/src/main.js, client/src/pages/editor.js
implements #2
this needs a Q server with https://github.com/nzzdev/Q-server/pull/43
=> translates tool names and title properties in schema

client/src/elements/item-preview/item-preview.js
=> sets ignoreInactive and noCache for preview

client/config.js, client/src/elements/item-preview/item-preview.js, client/src/livingdocs-component-app/app.js
=> Adds isPure option to rendering info request for preview

client/src/elements/schema-editor/schema-editor-array.js, client/src/elements/schema-editor/schema-editor.css, client/src/resources/SchemaEditorInputAvailabilityChecker.js, client/src/resources/schema-editor-decorators/checkAvailability.js
This can be tested with Quiz release branch containing an unavailableMessage in case `ItemHasId` check fails.
=> feat: let availabilityCheck define a message to show if unavailable

client/src/resources/schema-editor-decorators/checkAvailability.js
This makes for a cleaner object without these `__` pre- and postfixed properties.
=> use WeakMap instead of hidden properties in checkAvailability decorator

client/src/resources/ItemStore.js
search indexes are already extended by subtitle
```
if (doc.subtitle) {
index("subtitle", doc.subtitle);
}
```
=> Add subtitle to search query

client/locales/de/translation.json, client/locales/en/translation.json, client/src/elements/molecules/item-list-entry.css, client/src/elements/molecules/item-list-entry.html, client/src/pages/item-overview.css, client/src/pages/item-overview.html
This shows information about who updated a graphic at what date next to the name of the user who created an item.
=> Feat item edited by info

client/src/elements/schema-editor/helpers.js, client/src/elements/schema-editor/schema-editor-geojson-point.html, client/src/elements/schema-editor/schema-editor-geojson-point.js, client/src/elements/schema-editor/schema-editor-object.js
=> fix(geojson-point): handle required attribute on lat and lng inputs

CHANGELOG.md, client/config.js, client/locales/de/translation.json, client/locales/en/translation.json, client/package-lock.json, client/package.json, client/src/elements/item-preview/preview-container.html, client/src/elements/organisms/meta-editor.html, client/src/elements/schema-editor/schema-editor-array.html, client/src/elements/schema-editor/schema-editor-array.js, client/src/resources/ObjectFromSchemaGenerator.js, package-lock.json, package.json
=> Release 1.5.1

client/src/elements/schema-editor/schema-editor-table.html, client/src/elements/schema-editor/schema-editor-table.js
option defaults to true for backwards compatibility.
implements: https://github.com/nzzdev/Q-editor/issues/77
=> (schema-editor-table) add option allowTranspose

client/.eslintrc.json, client/src/elements/schema-editor/schema-editor-files.js
in dropzone thumbnail / prettier formatting
=> (schema-editor-files) keep aspect ratio of uploaded images

client/src/elements/organisms/meta-editor.html, client/src/resources/Item.js, client/src/resources/ItemStore.js
- apply prettier for formatting
- store the users acronym on the item in the same way as department is stored
- used to display acronym in the footer of some graphics
=> Feat acronym on item

client/locales/de/translation.json, client/locales/en/translation.json, client/src/elements/schema-editor/schema-editor-files.js
- With this PR the dropzone shows a different message if only one file is allowed
=> Show different dropzone message if only one file is allowed

CHANGELOG.md, client/locales/de/translation.json, client/locales/en/translation.json, client/src/elements/schema-editor/schema-editor-files.js, client/src/elements/schema-editor/schema-editor-textarea.html, package-lock.json, package.json
=> Release 1.7.1

client/src/elements/schema-editor/schema-editor-table.css
The scrollbar from the table in the editor is now bolder and therefore easier to use
=> scrollbar in editor

client/src/elements/schema-editor/schema-editor-table.js
Column resized so you can see all characters of a date
=> resized the column-width of the table in editor

client/src/elements/molecules/item-list-entry.css, client/src/elements/molecules/item-list-entry.html, client/src/elements/molecules/item-list-entry.js
Items will now open in a new tab and not on the same page
=> make item list entry an a tag to be able to open in new window

client/src/elements/molecules/language-switcher.html, client/src/elements/molecules/language-switcher.js, client/src/elements/molecules/radio-button-group.css, client/src/elements/organisms/q-bar.css, client/src/pages/editor.html, client/src/pages/item-overview.html
- improves language switcher styling
- shows language switcher on all pages (if more than one language configured in editor config)
=> (language-switcher) improve styling of language switcher

CHANGELOG.md, client/src/livingdocs-component-app/app.js, client/src/resources/schema-editor-decorators/resolveDynamicEnum.js, package-lock.json, package.json
- Fixes livingdocs-preview for items which are already included in an article
- fixes dynamicEnum in combination with translated schema
=> Release 3.0.2

client/src/binding-behaviors/ToolTBindingBehaviour.js, client/src/binding-behaviors/index.js, client/src/elements/schema-editor/schema-editor-array.html, client/src/elements/schema-editor/schema-editor-base64image.html, client/src/elements/schema-editor/schema-editor-boolean.html, client/src/elements/schema-editor/schema-editor-color.html, client/src/elements/schema-editor/schema-editor-date.html, client/src/elements/schema-editor/schema-editor-json.html, client/src/elements/schema-editor/schema-editor-link.html, client/src/elements/schema-editor/schema-editor-number.html, client/src/elements/schema-editor/schema-editor-object.html, client/src/elements/schema-editor/schema-editor-select.html, client/src/elements/schema-editor/schema-editor-string.html, client/src/elements/schema-editor/schema-editor-table.html, client/src/elements/schema-editor/schema-editor-textarea.html, client/src/elements/schema-editor/schema-editor-url.html, client/src/main.js, client/src/pages/editor.js, client/src/value-converters/ToolTValueConverter.js, client/src/value-converters/index.js
- refactors the schema translation to translate in the template using a special binding behaviour prepending the current tools name to the string for correct namespace
=> Feat schema translation

client/src/livingdocs-component-app/app.js, client/src/pages/index.js
- This PR fixes a bug where items where loaded twice in some circumstances
- This branch is deployed on https://q.st-test.nzz.ch/index for testing
=> Fixes bug where items where loaded twice

CHANGELOG.md, client/src/elements/atoms/button-primary.css, client/src/elements/atoms/button-primary.html, client/src/elements/atoms/button-secondary.css, client/src/elements/atoms/button-secondary.html, client/src/elements/atoms/button-tertiary.css, client/src/elements/atoms/button-tertiary.html, client/src/elements/atoms/icon-button.css, client/src/elements/atoms/icon-button.html, client/src/elements/atoms/icon-button.js, client/src/elements/organisms/tool-status-bar.html, client/src/elements/organisms/tool-status-bar.js, client/src/elements/schema-editor/schema-editor-array.js, client/src/pages/editor.js, client/src/resources/Item.js, client/src/value-converters/ToolTValueConverter.js, package-lock.json, package.json
- fix: do not allow two concurrent save requests
- fix: do not translate undefined for schema-editor strings
this is deployed on stage.
=> Release 3.0.5

client/config.js, client/package.json, client/src/elements/schema-editor/schema-editor-files.js
=> (WIP) File upload improvements

client/src/elements/item-preview/preview-container.css, client/src/elements/item-preview/preview-container.html, client/src/livingdocs-component-app/app.css, client/src/livingdocs-component-app/app.html
- Makes displayOptions container scrollable ( Fixes -> https://3.basecamp.com/3500782/buckets/1333707/todos/1343124605)
- Fixes cutoff border of preview
- This branch is deployed on staging
=> Fix styling of livingdocs preview 

client/src/resources/ObjectFromSchemaGenerator.js
- fixes blueprinting of items with files objects (they use implicit properties not defined in the json schema as properties on the object)
- this is deployed on test env
- fixes #172
=> (blueprint) fix blueprinting of items with special types

client/src/elements/schema-editor/schema-editor-table.js
- trims all cells whenever the data in handsontable changes
=> (schema-editor-table) trim all strings in all cells

client/locales/de/translation.json, client/locales/en/translation.json, client/locales/fr/translation.json, client/src/app.js, client/src/pages/editor.js, client/src/pages/tasks.css, client/src/pages/tasks.html, client/src/pages/tasks.js, client/src/resources/CurrentItemProvider.js, client/src/value-converters/JsonValueConverter.js, client/src/value-converters/ToolTValueConverter.js, routes/index.js
Created page for displaying tasks
- input able to display schema-editor
- output able to display json 
Deployed on st-test
=> Feat tasks page

client/index.html, client/locales/de/translation.json, client/locales/en/translation.json, client/locales/fr/translation.json, client/src/pages/login.html, client/src/pages/login.js
=> Remove browser detection

client/locales/de/translation.json, client/locales/en/translation.json, client/locales/fr/translation.json, client/src/pages/login.js
Closes #210 
I'm not sure if the error-messages are accurate enough. What do you think @manuelroth @benib ?
=> implemented better login error messages

.travis.yml, index.js, package-lock.json, package.json
- Updates hapi packages to use new organization packages ([old ones are no longer supported](https://www.npmjs.com/package/hapi))
=> Update hapi packages to use organization prefix

client/src/resources/CurrentItemProvider.js, client/src/resources/checkers/AvailabilityChecker.js, client/src/resources/checkers/NotificationChecker.js, client/src/resources/checkers/ToolEndpointChecker.js, client/src/resources/notification-checks/EmptyDataNotificationCheck.js, client/src/resources/notification-checks/HasColumnTitlesNotificationCheck.js, client/src/resources/notification-checks/TooManyColumnsNotificationCheck.js, client/src/resources/schema-editor-decorators/resolveDynamicEnum.js
This PR removes the transformation of old check config and the deprecation notice as all tools have adopted the new check config
=> Removes deprecation notice for check config

client/src/elements/schema-editor/schema-editor-wrapper.js, client/src/resources/schema-editor-decorators/resolveDynamicEnum.js
- fixes the issue where `notificationChecks` and `availabilityChecks` are applied multiple times if `dynamicSchema` is used
=> Fix dynamic schema notification checks

CHANGELOG.md, client/src/elements/schema-editor/schema-editor-wrapper.js, client/src/resources/schema-editor-decorators/resolveDynamicEnum.js, package-lock.json, package.json
-fix: do not apply notificationChecks and availabilityChecks more than once, forbid them in dynamicSchema
=> Release 4.0.1

client/src/livingdocs-component-app/app.js
=> load fonts in livingsdocs preview

client/config.js, client/src/elements/schema-editor/schema-editor-code.js, package-lock.json, package.json
This PR is a bugfix release which fixes the loading of CSS styles of the codemirror editor
=> Releases v5.0.1

client/config.js, client/package.json, client/src/elements/schema-editor/schema-editor-geojson-point.css, client/src/elements/schema-editor/schema-editor-geojson-point.js
Fixes https://3.basecamp.com/3500782/buckets/1333707/todos/2090157590
=> Prevent collapsing array item if enter key is pressed after search

CHANGELOG.md, client/src/dialogs/export-dialog.js, client/src/resources/schema-editor-decorators/resolveDynamicEnum.js, package-lock.json, package.json
- fix: correctly append the extension to the filename on export
=> Release 6.0.1

CHANGELOG.md, client/src/livingdocs-component-app/app.js, package-lock.json, package.json
- feat: use new display-options route in livingdocs-component which makes display-options more configurable
=> Releases v6.1.0

client/package-lock.json, client/src/livingdocs-component-app/app.css, client/src/livingdocs-component-app/app.html
closes https://tracking.nzzmg.ch/browse/WCMS-5024
- removes flexbox around display options form
- sets a max height on this form and adds a scrollbar in case it's bigger
=> Fix ld component for many display options

CHANGELOG.md, client/package-lock.json, client/src/livingdocs-component-app/app.css, client/src/livingdocs-component-app/app.html, package-lock.json, package.json
- fix: preview not visible if too many displayOptions in livingdocs-component
=> Release 6.1.3

CHANGELOG.md, client/src/elements/item-preview/item-preview.css, client/src/livingdocs-component-app/app.css, package-lock.json, package.json
- feat: change preview padding from 16px to 24px
=> Release 6.1.4

CHANGELOG.md, client/src/dialogs/schema-editor-dialog.js, client/src/elements/schema-editor/schema-editor-bbox.js, client/src/elements/schema-editor/schema-editor-geojson-point.js, client/src/pages/editor.js, client/src/resources/checkers/ToolEndpointChecker.js, package-lock.json, package.json
- feat: awaits ToolEndpointChecks before rendering the preview
- feat: `schema-editor-bbox` takes an optional bounds property
- feat: `schema-editor-geojson` increases search input debounce value to one second
=> Release 6.2.0

CHANGELOG.md, client/src/elements/schema-editor/schema-editor-geojson-point.js, package-lock.json, package.json
- fix: (schema-editor-geojson-point) Implement change detection of coordinate property
=> Release v6.2.1

CHANGELOG.md, client/src/pages/editor.html, package-lock.json, package.json
- (editor-page) If item id is not available yet, back button should point to index page
=> Release 6.2.2

CHANGELOG.md, client/config.js, client/package.json, client/src/elements/schema-editor/schema-editor-geojson-point.css, client/src/elements/schema-editor/schema-editor-geojson-point.js, package-lock.json, package.json
- feat: (schema-editor-geojson-point) Use maptiler geocoder
=> Release v6.2.3

client/config.js, client/package.json
Fixes #271.
Fixed in https://github.com/nzzdev/handsontable/commit/45811f2a45b08e5165b24bd3a7b65cc9ab79c7af in patched fork of handsontable.
=> Use patched version of handsontable

CHANGELOG.md, client/config.js, client/package.json, package-lock.json, package.json
- Fix: Use patched version of handsontable
=> Release v6.2.4

CHANGELOG.md, client/src/elements/schema-editor/schema-editor-table.js, client/src/elements/schema-editor/schema-editor-wrapper.js, package-lock.json, package.json
* adds support for readOnly cells and predefined content
=> Release 6.3.0

CHANGELOG.md, client/src/elements/schema-editor/schema-editor-table.js, client/src/elements/schema-editor/schema-editor-wrapper.js, package-lock.json, package.json
- fix: (schema-editor-table) ignore rows/columns which differ of range of predefinedValues
- fix: (dynamic-schema) apply default values which are defined in dynamicSchema
=> Release 6.3.1

CHANGELOG.md, client/config.js, client/package-lock.json, client/package.json, client/src/elements/schema-editor/schema-editor-array.css, client/src/elements/schema-editor/schema-editor-color.css, client/src/elements/schema-editor/schema-editor-color.html, package-lock.json, package.json
- (schema-editor-array) Improve styles of schema-editor-array__entry-container--compact
- (schema-editor-color) show color input as text input
=> Release 6.3.4

client/src/main.js, client/src/resources/User.js
This PR makes sure that cookies are sent with authentication requests to q-server
=> Use credentials: include in httpClient

client/config.js, client/src/main.js, client/src/resources/User.js, package-lock.json, package.json
- Makes sure that cookies are sent with authentication requests to q-server
=> Release 6.3.5

CHANGELOG.md, client/src/resources/Auth.js, client/src/resources/Item.js, client/src/resources/User.js, package-lock.json, package.json
- Set `credentials: "include"` setting selectively
=> Release 6.3.6

CHANGELOG.md, client/src/dialogs/export-dialog.js, client/src/elements/item-preview/item-preview.js, client/src/livingdocs-component-app/app.js, client/src/pages/feed.js, package-lock.json, package.json
- fix: (preview) Use encodeURIComponent instead of encodeURI to encode toolRuntimeConfig in renderingInfo request so that reserved characters are getting encoded (Fixes [https://3.basecamp.com/3500782/buckets/1333707/todos/3586797477](https://3.basecamp.com/3500782/buckets/1333707/todos/3586797477))
=> Release 6.3.7

CHANGELOG.md, client/src/elements/schema-editor/schema-editor-files.js, package-lock.json, package.json
- (schema-editor-files) Send credentials with `/file` request
=> Release 6.3.8

CHANGELOG.md, client/src/resources/checkers/ToolEndpointChecker.js, package-lock.json, package.json
- (ToolEndpointChecker) Send roles with every toolEndpoint request. This allows to use the roles information to calculate toolEndpoint results
=> Release 6.4.0

CHANGELOG.md, client/package-lock.json, client/src/elements/schema-editor/schema-editor-number.html, client/src/elements/schema-editor/schema-editor-number.js, package-lock.json, package.json
- fix: (schema-editor-number) Prevent value change on wheel event
=> Release 6.4.1

client/src/resources/checkers/NotificationChecker.js
- Notifications are now correctly sorted by their given priority (0 = lowest priority, 10 = highest priority)
=> fix priority sorting of notifications

client/src/elements/schema-editor/schema-editor-geojson-point.js, package-lock.json, package.json
Set user language to de & en for geolocator queries used in q-locator-map
=> Release 6.5.2

client/src/dialogs/export-dialog.js, package-lock.json, package.json
- Abort pending request on export setting change
=> Release 6.5.3
